# Generated by Django 5.1.2 on 2024-11-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wahlergebnis_WBZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wahl', models.CharField(max_length=7)),
                ('WKNr', models.CharField(max_length=4)),
                ('WKName', models.CharField(max_length=100)),
                ('Ebene', models.CharField(max_length=10)),
                ('AGS', models.CharField(max_length=8)),
                ('Ortname', models.CharField(max_length=50)),
                ('Briefwahl_Sonderfall', models.CharField(blank=True, max_length=50, null=True)),
                ('WBZArt', models.CharField(max_length=50)),
                ('WBZNr', models.CharField(max_length=50)),
                ('WBZName', models.CharField(max_length=50)),
                ('Wahlberechtigte', models.IntegerField()),
                ('Wähler', models.IntegerField()),
                ('Stimmart', models.CharField(max_length=1)),
                ('ungueltige', models.IntegerField()),
                ('gueltige', models.IntegerField()),
                ('Partei', models.CharField(max_length=30)),
                ('Stimmen', models.IntegerField()),
                ('aktualisiert_am', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
