# Generated by Django 5.1.2 on 2024-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergebnisse_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wahlergebnis_wbz',
            name='Ortname',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='wahlergebnis_wbz',
            name='WBZArt',
            field=models.CharField(max_length=70),
        ),
    ]
