# Generated by Django 5.1.2 on 2024-11-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ergebnisse_api', '0002_alter_wahlergebnis_wbz_ortname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wahlergebnis_wbz',
            name='WBZName',
            field=models.CharField(max_length=70),
        ),
    ]
